# Generated by GitHub Copilot on 2025-10-04
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='pages_page_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published', 'published_at'], name='pages_page_published_idx'),
        ),
    ]
