# Generated by Django 5.2.6 on 2025-10-03 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting us', max_length=100)),
                ('email', models.EmailField(help_text='Valid email address for response', max_length=254)),
                ('subject', models.CharField(default='General Inquiry', help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='The contact message content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this message was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Whether admin has read this message')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
